ALTER TABLE users
  ADD COLUMN IF NOT EXISTS country VARCHAR(100) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS bio TEXT NOT NULL DEFAULT '';

ALTER TABLE user_data
  ADD COLUMN IF NOT EXISTS payment_json JSONB NOT NULL DEFAULT '{}';
