-- Seed: Owner Default SEO Templates (090826 Foundation)
-- NOT SEO strategy lock — epic 040826 may refine later.
-- Dynamic pages keep {placeholders}; public effective strips unresolved templates.

INSERT INTO page_seo_configs (page_key, payload, updated_at, updated_by)
VALUES
('dashboard', '{"seoTitle":"Nhà của tôi | iFlux","metaDescription":"Theo dõi danh mục, thị trường, dòng tiền và những thông tin tài chính quan trọng của bạn trên iFlux.","seoTier":"utility","baselineKind":"default_seo_template","baselineSource":"owner-seo-baseline-2026-08-09","hasPlaceholders":false}'::jsonb, NOW(), 'owner-seo-baseline'),
('market', '{"seoTitle":"Thị trường chứng khoán | iFlux","metaDescription":"Cập nhật thị trường chứng khoán, diễn biến giá, nhóm ngành và các tín hiệu dòng tiền nổi bật trên iFlux.","seoTier":"tier1","baselineKind":"default_seo_template","baselineSource":"owner-seo-baseline-2026-08-09","hasPlaceholders":false}'::jsonb, NOW(), 'owner-seo-baseline'),
('community', '{"seoTitle":"Cộng đồng chứng khoán | iFlux","metaDescription":"Khám phá bài viết, góc nhìn và chia sẻ từ cộng đồng nhà đầu tư về chứng khoán, thị trường và dòng tiền.","seoTier":"tier1","baselineKind":"default_seo_template","baselineSource":"owner-seo-baseline-2026-08-09","hasPlaceholders":false}'::jsonb, NOW(), 'owner-seo-baseline'),
('flow', '{"seoTitle":"Dòng tiền chứng khoán | iFlux","metaDescription":"Phân tích dòng tiền trên thị trường chứng khoán, theo dõi xu hướng vận động và những nhóm đang thu hút dòng tiền.","seoTier":"tier1","baselineKind":"default_seo_template","baselineSource":"owner-seo-baseline-2026-08-09","hasPlaceholders":false}'::jsonb, NOW(), 'owner-seo-baseline'),
('membership', '{"seoTitle":"Membership iFlux | Quyền lợi thành viên","metaDescription":"Khám phá các gói Membership, quyền lợi và trải nghiệm dành cho thành viên iFlux khi theo dõi thị trường chứng khoán.","seoTier":"tier2","baselineKind":"default_seo_template","baselineSource":"owner-seo-baseline-2026-08-09","hasPlaceholders":false}'::jsonb, NOW(), 'owner-seo-baseline'),
('faq', '{"seoTitle":"Câu hỏi thường gặp | iFlux","metaDescription":"Tìm câu trả lời về iFlux, tài khoản, Membership, tính năng, dữ liệu thị trường và cách sử dụng nền tảng.","seoTier":"tier2","baselineKind":"default_seo_template","baselineSource":"owner-seo-baseline-2026-08-09","hasPlaceholders":false}'::jsonb, NOW(), 'owner-seo-baseline'),
('account', '{"seoTitle":"Trang cá nhân | iFlux","metaDescription":"Quản lý thông tin cá nhân, tài khoản và các thiết lập trải nghiệm của bạn trên iFlux.","seoTier":"utility","baselineKind":"default_seo_template","baselineSource":"owner-seo-baseline-2026-08-09","hasPlaceholders":false}'::jsonb, NOW(), 'owner-seo-baseline'),
('messages', '{"seoTitle":"Tin nhắn | iFlux","metaDescription":"Quản lý tin nhắn và trao đổi của bạn với cộng đồng trên iFlux.","seoTier":"utility","baselineKind":"default_seo_template","baselineSource":"owner-seo-baseline-2026-08-09","hasPlaceholders":false}'::jsonb, NOW(), 'owner-seo-baseline'),
('stocks', '{"seoTitle":"Danh sách cổ phiếu | iFlux","metaDescription":"Tra cứu cổ phiếu trên thị trường chứng khoán, khám phá doanh nghiệp và theo dõi các mã cổ phiếu trên iFlux.","seoTier":"tier1","baselineKind":"default_seo_template","baselineSource":"owner-seo-baseline-2026-08-09","hasPlaceholders":false}'::jsonb, NOW(), 'owner-seo-baseline'),
('stock-detail', '{"seoTitle":"{Tên cổ phiếu} ({Mã}) | iFlux","metaDescription":"Xem thông tin, diễn biến và các dữ liệu liên quan đến {Tên cổ phiếu} ({Mã}) trên iFlux.","seoTier":"tier1","baselineKind":"default_seo_template","baselineSource":"owner-seo-baseline-2026-08-09","hasPlaceholders":true}'::jsonb, NOW(), 'owner-seo-baseline'),
('sectors', '{"seoTitle":"Ngành chứng khoán | iFlux","metaDescription":"Khám phá các ngành trên thị trường chứng khoán, theo dõi doanh nghiệp, diễn biến và dòng tiền theo từng ngành.","seoTier":"tier1","baselineKind":"default_seo_template","baselineSource":"owner-seo-baseline-2026-08-09","hasPlaceholders":false}'::jsonb, NOW(), 'owner-seo-baseline'),
('sector-detail', '{"seoTitle":"{Tên ngành} | iFlux","metaDescription":"Khám phá thông tin, cổ phiếu và diễn biến dòng tiền của ngành {Tên ngành} trên thị trường chứng khoán.","seoTier":"tier1","baselineKind":"default_seo_template","baselineSource":"owner-seo-baseline-2026-08-09","hasPlaceholders":true}'::jsonb, NOW(), 'owner-seo-baseline'),
('ecosystems', '{"seoTitle":"Hệ sinh thái doanh nghiệp | iFlux","metaDescription":"Khám phá các hệ sinh thái doanh nghiệp, nhóm cổ phiếu liên quan và dòng tiền theo từng hệ sinh thái trên iFlux.","seoTier":"tier1","baselineKind":"default_seo_template","baselineSource":"owner-seo-baseline-2026-08-09","hasPlaceholders":false}'::jsonb, NOW(), 'owner-seo-baseline'),
('eco-detail', '{"seoTitle":"{Tên hệ sinh thái} | iFlux","metaDescription":"Khám phá các doanh nghiệp, cổ phiếu và mối liên hệ trong hệ sinh thái {Tên hệ sinh thái} trên iFlux.","seoTier":"tier1","baselineKind":"default_seo_template","baselineSource":"owner-seo-baseline-2026-08-09","hasPlaceholders":true}'::jsonb, NOW(), 'owner-seo-baseline'),
('cau-chuyen', '{"seoTitle":"Câu chuyện thị trường | iFlux","metaDescription":"Khám phá những câu chuyện nổi bật đang diễn ra trên thị trường chứng khoán và các doanh nghiệp được quan tâm.","seoTier":"tier1","baselineKind":"default_seo_template","baselineSource":"owner-seo-baseline-2026-08-09","hasPlaceholders":false}'::jsonb, NOW(), 'owner-seo-baseline'),
('cau-chuyen-detail', '{"seoTitle":"{Tên câu chuyện} | iFlux","metaDescription":"Khám phá câu chuyện {Tên câu chuyện}, các doanh nghiệp, cổ phiếu và diễn biến liên quan trên thị trường.","seoTier":"tier1","baselineKind":"default_seo_template","baselineSource":"owner-seo-baseline-2026-08-09","hasPlaceholders":true}'::jsonb, NOW(), 'owner-seo-baseline'),
('com-topic', '{"seoTitle":"Chủ đề Cộng đồng | iFlux","metaDescription":"Khám phá các chủ đề được quan tâm trong cộng đồng iFlux và những bài viết, góc nhìn liên quan đến từng chủ đề.","seoTier":"tier1","baselineKind":"default_seo_template","baselineSource":"owner-seo-baseline-2026-08-09","hasPlaceholders":false}'::jsonb, NOW(), 'owner-seo-baseline'),
('com-cat', '{"seoTitle":"{Tên danh mục} | Cộng đồng iFlux","metaDescription":"Khám phá các bài viết thuộc danh mục {Tên danh mục} và những góc nhìn đáng chú ý từ cộng đồng iFlux.","seoTier":"tier1","baselineKind":"default_seo_template","baselineSource":"owner-seo-baseline-2026-08-09","hasPlaceholders":true}'::jsonb, NOW(), 'owner-seo-baseline'),
('com-author', '{"seoTitle":"{Tên tác giả} | Cộng đồng iFlux","metaDescription":"Khám phá hồ sơ, bài viết và những chia sẻ của {Tên tác giả} trong cộng đồng iFlux.","seoTier":"tier2","baselineKind":"default_seo_template","baselineSource":"owner-seo-baseline-2026-08-09","hasPlaceholders":true}'::jsonb, NOW(), 'owner-seo-baseline')
ON CONFLICT (page_key) DO UPDATE SET
  payload = page_seo_configs.payload || EXCLUDED.payload,
  updated_at = NOW(),
  updated_by = EXCLUDED.updated_by;
