'use strict';

const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  SYNC_CONFLICT: 'SYNC_CONFLICT',
  PREMIUM_REQUIRED: 'PREMIUM_REQUIRED',
  TIER_EXPIRED: 'TIER_EXPIRED',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
});

module.exports = { ERROR_CODES };
